# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 155786b4e6213069c4b00285a79307228e62d0a3663063c1456c25a4c6fd56c773a36c45f6a15fefca209eaa30d2eba12364bfdd98f1992f3dcff787fa22fc06

test:
  secret_key_base: cac4f73e4937f84cfe7147fd95bdf534f1a8aa2982298565d1a53a7c8a445d9a6ef975a636bafc64939b3e7984c0df6d99492760eea2d3edae3c39d11d52e3e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
